{
  "ambient": {
    "X": 0.0,
    "Y": 0.0,
    "Z": 0.0,
    "W": 1.0
  },
  "diffuse": {
    "X": 1.0,
    "Y": 1.0,
    "Z": 1.0,
    "W": 1.0
  },
  "specular": {
    "X": 1.0,
    "Y": 1.0,
    "Z": 1.0,
    "W": 1.0
  },
  "cutOff": 5.0,
  "outerCutOff": 10.0,
  "add": true,
  "type": "TheSimulation.SerializedComponent.SpotLightSerialized, SimulationWFA, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"
}